\clearpage

# Tables {#sec:tables}

```{r}

#mw5ABCD <- read_csv(here::here("data/results/AnnualMeanWeight_5ABCD.csv"))
#mw3CD <- read_csv(here::here("data/results/AnnualMeanWeight_3CD.csv"))

```


```{r tab-param-est-table-3cd, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$","$B_0$")
make.parameters.est.table(base.model.3cd,
  caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
    "97.5\\textsuperscript{th} percentile) and MPD ",
    "estimates of key parameters from the Reference Case, Area 3CD. $R_0$ is in thousands of fish. $\\hat{R}$ is the potential scale reduction statistic and $n_\\mathrm{eff}$ is the effective number of simulation draws (see text). ",
    q.3cd.desc),
  omit_pars = pars_est_omit, french=french)
```


```{r tab-param-est-table-3cd-sc1, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$","$B_0$")
make.parameters.est.table(sens.models.00[[1]],
  caption = paste0("Same as the reference case table, but for Sc 1 (no mean weight index for 2018-2020)"),
  omit_pars = pars_est_omit, french=french)
```


```{r tab-param-est-table-3cd-sc2, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$","$B_0$")
make.parameters.est.table(sens.models.00[[2]],
  caption = paste0("Same as the reference case table, but for Sc 2 (2016 mean weight value for 2018-2020)"),
  omit_pars = pars_est_omit, french=french)
```

\clearpage

```{r tab-param-est-table-5abcd, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$", "$B_0$")
make.parameters.est.table(base.model.5abcd,
  caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
    "97.5\\textsuperscript{th} percentile) and MPD ",
    "estimates of key parameters from the Reference Case, Area 5ABCD. $R_0$ is in thousands of fish. $\\hat{R}$ is the potential scale reduction statistic and $n_\\mathrm{eff}$ is the effective number of simulation draws (see text). ",
    q.5abcd.desc),
  omit_pars = pars_est_omit, french=french)
```


```{r tab-param-est-table-5abcd-sc1, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$","$B_0$")
make.parameters.est.table(sens.models.0[[1]],
  caption = paste0("Same as the reference case table, but for Sc 1 (no mean weight index for 2018-2020"),
  omit_pars = pars_est_omit, french=french)
```


```{r tab-param-est-table-5abcd-sc2, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$","$B_0$")
make.parameters.est.table(sens.models.0[[2]],
  caption = paste0("Same as the reference case table, but for Sc 2 (2016 mean weight value for 2018-2020"),
  omit_pars = pars_est_omit, french=french)
```


\clearpage
